### ISSUE TITLE
Kanban SetUp For Rails Recipe-App

### ISSUE THREAD

**Issue by Dinma-Faith-zz** [Dinma-Faith-zz/Recipe-App#12]
Hello,
 [here](https://github.com/users/Dinma-Faith/projects/1)'s the link to our project:

 We are two partners working on this project :
- @Dinma-Faith 
- @Yorsyboy

Thank you

**Comment by zhadier** [comment]
# Hi @Dinma-Faith & @Yorsyboy  👋 

Good job so far! 🌤️ 
There are some issues that you still need to work on to go to the next project but you are almost there! 🍓 

<img src="https://media4.giphy.com/media/5wWf7GR2nhgamhRnEuA/giphy.gif"/>

## Highlights

✔️ Great task description and distribution.


## Required Changes ♻️

- [x] Kindly alter this column heading to be `In Review` instead of `In View`
![image](https://user-images.githubusercontent.com/90556221/187185132-d01a7dba-caa7-4329-af4f-42d9ae15df3f.png)

- [x] Kindly assign some points to the Setup repository task aswell.
![image](https://user-images.githubusercontent.com/90556221/187185249-b3046d19-713e-4472-a10c-39a531d84150.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question @zhadier so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Dinma-Faith-zz** [comment]
@zhadier Thanks for your review.

**Comment by aimemalaika** [comment]
Hi @Dinma-Faith & @Yorsyboy, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
